id: P007009
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22949
  title: ལྷུག་རྩོམ་སྙན་འཇེབས་ཚིག་གི་བདུད་རྩི།
  author: ''
  volumes:
    e9f07ba948c74b6ebdc98b00e1e8d9d1:
      image_group_id: I1KG23014
      title: ''
      volume_number: 1
      total_pages: 290
ebook_metadata:
  title: ལྷུག་རྩོམ་སྙན་འཇེབས་ཚིག་གི་བདུད་རྩི།
  author: ''
  sku: P007009
  cover: cover.jpg
  layers:
  - pagination
