id: opecha:P007009
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22949
  title: ལྷུག་རྩོམ་སྙན་འཇེབས་ཚིག་གི་བདུད་རྩི།
  volume:
    c4bf838c3b4548fdbb0d5a84ca60b1b1:
      image_group_id: I1KG23014
      title: Volume 1 of lhug rtsom snyan 'jebs tshig gi bdud rtsi/
      volume_number: 1
      total_pages: 290
  author: ''
ebook_metadata:
  title: ལྷུག་རྩོམ་སྙན་འཇེབས་ཚིག་གི་བདུད་རྩི།
  author: ''
  sku: P007009
  cover: cover.jpg
  layers:
  - pagination
