id: P007009
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:35:58.675009
source_metadata:
  id: bdr:W1KG22949
  title: ལྷུག་རྩོམ་སྙན་འཇེབས་ཚིག་གི་བདུད་རྩི།
  author: ''
  volumes:
    c4bf838c3b4548fdbb0d5a84ca60b1b1:
      image_group_id: I1KG23014
      title: Volume 1 of lhug rtsom snyan 'jebs tshig gi bdud rtsi/
      volume_number: 1
      total_pages: 290
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
