id: IBBF0C3A4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T19:24:00+00:00'
last_modified: '2022-06-08T11:56:32.235607+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22949
  title: ལྷུག་རྩོམ་སྙན་འཇེབས་ཚིག་གི་བདུད་རྩི།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    42B0:
      image_group_id: I1KG23014
      title: Volume 1 of lhug rtsom snyan 'jebs tshig gi bdud rtsi/
      total_pages: 290
      order: 1
      base_file: 42B0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
